### ISSUE TITLE
Set a default value for `directory`

### ISSUE THREAD

**Issue by aminya** [KyleMayes/install-llvm-action#10]
I have to write a custom script just to specify the installation path whenever I need to use this action, while it could be handled internally if it had a reasonable default value. 🤔 

Here is how I have to use this action.
```yaml
      - name: Set LLVM Installation Path
        shell: pwsh
        run: |
          if ("${{ matrix.os }}" -like 'windows*') {
            $LLVM_PATH = "C:/Program Files/LLVM"
          } elseif ("${{ matrix.os }}" -like 'ubuntu*') {
            $LLVM_PATH = "${{ runner.temp }}/llvm"
          }
          echo "$LLVM_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$LLVM_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "LLVM_PATH=$LLVM_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1.3.0
        with:
          version: 10
          directory: ${{ env.LLVM_PATH }}
```
