### ISSUE TITLE
libLLVM.so is missing

### ISSUE THREAD

**Issue by dannypsnl** [KyleMayes/install-llvm-action#17]
configuration
```yaml
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
```
when finding `libLLVM`
```
libLLVM.so: cannot open shared object file: No such file or directory
```
