### ISSUE TITLE
Configuration not fully completed?

### ISSUE THREAD

**Issue by tdegeus** [KyleMayes/install-llvm-action#4]
Thanks for the action! However, in trying to use with CMake
```yaml
    - name: Install LLVM and Clang (Windows)
      if: runner.os == 'Windows'
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm

    - name: Configure using CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        conda install -c conda-forge ninja
        cmake . -G Ninja -DCMAKE_C_COMPILER="clang-cl.exe" -DCMAKE_CXX_COMPILER="clang-cl.exe"
```
I encounter the problem that
```bash
-- The C compiler identification is Clang 11.0.0 with MSVC-like command-line
-- The CXX compiler identification is Clang 11.0.0 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: D:/a/_temp/llvm/bin/clang-cl.exe
-- Check for working C compiler: D:/a/_temp/llvm/bin/clang-cl.exe - broken
CMake Error at C:/Miniconda/envs/test/Library/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "D:/a/_temp/llvm/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/a/GooseFEM/GooseFEM/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Miniconda/envs/test/Library/bin/ninja.exe cmTC_022df && [1/2] Building C object CMakeFiles\cmTC_022df.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_022df.exe
    FAILED: cmTC_022df.exe 
    cmd.exe /C "cd . && C:\Miniconda\envs\test\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_022df.dir --rc=D:\a\_temp\llvm\bin\llvm-rc.exe --mt=CMAKE_MT-NOTFOUND --manifests  -- D:\a\_temp\llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_022df.dir\testCCompiler.c.obj  /out:cmTC_022df.exe /implib:cmTC_022df.lib /pdb:cmTC_022df.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "D:\a\_temp\llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_022df.dir\testCCompiler.c.obj /out:cmTC_022df.exe /implib:cmTC_022df.lib /pdb:cmTC_022df.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_022df.dir/intermediate.manifest CMakeFiles\cmTC_022df.dir/manifest.res" failed (exit code 1) with the following output:
-- Configuring incomplete, errors occurred!
See also "D:/a/GooseFEM/GooseFEM/CMakeFiles/CMakeOutput.log".
    lld-link: error: could not open 'kernel32.lib': no such file or directory
See also "D:/a/GooseFEM/GooseFEM/CMakeFiles/CMakeError.log".
    lld-link: error: could not open 'user32.lib': no such file or directory
    lld-link: error: could not open 'gdi32.lib': no such file or directory
    lld-link: error: could not open 'winspool.lib': no such file or directory
    lld-link: error: could not open 'shell32.lib': no such file or directory
    lld-link: error: could not open 'ole32.lib': no such file or directory
    lld-link: error: could not open 'oleaut32.lib': no such file or directory
    lld-link: error: could not open 'uuid.lib': no such file or directory
    lld-link: error: could not open 'comdlg32.lib': no such file or directory
    lld-link: error: could not open 'advapi32.lib': no such file or directory
    lld-link: error: could not open 'msvcrtd.lib': no such file or directory
    lld-link: error: could not open 'oldnames.lib': no such file or directory
    ninja: build stopped: subcommand failed.
```
How can this be solved?

FYI, I'm trying here : https://github.com/tdegeus/GooseFEM/pull/139
