### ISSUE TITLE
CMake can't find LLVM

### ISSUE THREAD

**Issue by Gashmob** [KyleMayes/install-llvm-action#40]
Hello there !

I make a compiler and I use LLVM as dependency. So in my CMakeLists.txt I've added :
```cmake
# ...

find_package(LLVM REQUIRED CONFIG)

message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")

include_directories(${LLVM_INCLUDE_DIRS})
separate_arguments(LLVM_DEFINITIONS_LIST NATIVE_COMMAND ${LLVM_DEFINITIONS})
add_definitions(${LLVM_DEFINITIONS})

llvm_map_components_to_libnames(llvm_libs support core irreader)

# ...

target_link_libraries(filc ${llvm_libs})

# ...
```

Then to run my tests I use your actions to install LLVM, for ubuntu and mac it works fine, but for windows I got this error :
```
-- Configuring incomplete, errors occurred!
  Could not find a package configuration file provided by "LLVM" with any of
See also "D:/a/Filc/Filc/build/CMakeFiles/CMakeOutput.log".
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Your actions install LLVM well :
```
Installing LLVM and Clang 10.0 (10.0.0)...
Downloading and extracting 'https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe'...
C:\ProgramData\Chocolatey\bin\7z.exe x D:\a\_temp\b509a76d-9a20-4bc9-8dd7-21dde6795761 "-oC:\Program Files\LLVM" -y

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 167786166 bytes (161 MiB)

Extracting archive: D:\a\_temp\b509a76d-9a20-4bc9-8dd7-21dde6795761
--
Path = D:\a\_temp\b509a76d-9a20-4bc9-8dd7-21dde6795761
Type = Nsis
Physical Size = 167786166
Method = LZMA:25
Solid = +
Headers Size = 219658
Embedded Stub Size = 114688
SubType = NSIS-3

Everything is Ok

Files: 359
Size:       1615649005
Compressed: 167786166
Installed LLVM and Clang 10.0 (10.0.0)!
Install location: C:\Program Files\LLVM
```

In my workflow I've write that :
```yml
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{github.workspace}}/build
```
I use version 10 as it's the version installed on my linux.

Did you have an idea of what I'm doing wrong ?
