### ISSUE TITLE
Installation slow

### ISSUE THREAD

**Issue by tdegeus** [KyleMayes/install-llvm-action#48]
I found some code to install clang compilers on linux:
```yaml
        LLVM_VERSION=${{ matrix.sys.version }}
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - || exit 1
        if [[ $LLVM_VERSION -ge 13 ]]; then
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-$LLVM_VERSION main" || exit 1
        else
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main" || exit 1
        fi || exit 1
        sudo apt-get update || exit 1
        sudo apt-get --no-install-suggests --no-install-recommends install clang-$LLVM_VERSION || exit 1
        sudo apt-get --no-install-suggests --no-install-recommends install g++-9 g++-9-multilib || exit 1
        sudo ln -s /usr/include/asm-generic /usr/include/asm
        CC=clang-$LLVM_VERSION
        echo "CC=$CC" >> $GITHUB_ENV
        CXX=clang++-$LLVM_VERSION
        echo "CXX=$CXX" >> $GITHUB_ENV
```
which takes my action 25sec. 

Instead
```yaml
    - name: Install LLVM and Clang
      if: runner.os == 'Linux'
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
```
takes my action **120sec**. I saw a note about caching. However, I wonder why it is so slow to begin with?
