### ISSUE TITLE
Error: Unsupported target! (platform='darwin', version='16.0.0')

### ISSUE THREAD

**Issue by masx200** [KyleMayes/install-llvm-action#49]
Error: Unsupported target! (platform='darwin', version='16.0.0')

https://formulae.brew.sh/formula/llvm#default

<html>
<body>
<p style="margin: 0px 0px 1em; color: rgb(249, 208, 148); font-family: -apple-system, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(46, 42, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Current versions:</p>

stable | ✅ | 16.0.3
-- | -- | --
head | ⚡️ | HEAD

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by masx200** [comment]
```yml
- uses: actions/cache@v3
              id: cache-llvm-16
              with:
                 path: |
                  /usr/local/opt/llvm
 
                  /usr/local/Cellar/llvm/
                 key: ${{ runner.os }}-llvm-16  
```

```yml

            - name: Install LLVM and Clang
        
              if: ${{ steps.cache-llvm-16.outputs.cache-hit!= 'true' }}
              run: brew install llvm@16
```

**Comment by KyleMayes** [comment]
Looks like the LLVM project has stopped making release binaries for non-ARM64 macOS:
https://github.com/llvm/llvm-project/releases

Whether purposefully or not, I don't know.

**Comment by dmlloyd** [comment]
As a workaround, I'm doing this:

```yaml
      - name: Install LLVM (Homebrew)
        if: matrix.os == 'macos-latest' && matrix.llvm-version == '16'
        run: |
            brew install llvm@${{ matrix.llvm-version }}
            echo /usr/local/opt/llvm@${{ matrix.llvm-version }}/bin >> $GITHUB_PATH
```

and adjusting my other actions accordingly.
