### ISSUE TITLE
error: 'format' file not found

### ISSUE THREAD

**Issue by Chamber6821** [KyleMayes/install-llvm-action#53]
I can't use header `<format>` after install LLVM 16

**Minimal example**

`main.cpp`:
```c++
#include <format>
#include <iostream>

int main() {
  std::setlocale(LC_ALL, "Russian");

  int cows = 33;
  std::wcout << std::format(
      L"{0} коровы, {0} коровы, {0} коровы - свежая строка\n", cows);
}

```

workflow:
```yml
on:
  push:
    branches: [ master ]
jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
      - run: clang++ main.cpp --std=c++20 --output=main
      - run: ./main
```

Output from GitHub:
```
Run clang++ main.cpp --std=c++20 --output=main
main.cpp:1:10: fatal error: 'format' file not found
#include <format>
         ^~~~~~~~
1 error generated.
Error: Process completed with exit code 1.
```
