### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by AshUK** [KyleMayes/install-llvm-action#72]
```
 - name: install llvm and clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '17.0.2'
```

```
Checking known assets (os=linux, arch=x64, version=17.0.2)...
Error: Unsupported version for platform (os=linux, arch=x64, version=17.0.2)!
```

Note sure what has gone wrong here as I see both versions in the assets.json file
